# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bazin_q/rendu/Perso/Asylia

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bazin_q/rendu/Perso/Asylia

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazin_q/rendu/Perso/Asylia/CMakeFiles /home/bazin_q/rendu/Perso/Asylia/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bazin_q/rendu/Perso/Asylia/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Asylia

# Build rule for target.
Asylia: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Asylia
.PHONY : Asylia

# fast build rule for target.
Asylia/fast:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/build
.PHONY : Asylia/fast

external/AndroidIO.o: external/AndroidIO.cpp.o

.PHONY : external/AndroidIO.o

# target to build an object file
external/AndroidIO.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/AndroidIO.cpp.o
.PHONY : external/AndroidIO.cpp.o

external/AndroidIO.i: external/AndroidIO.cpp.i

.PHONY : external/AndroidIO.i

# target to preprocess a source file
external/AndroidIO.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/AndroidIO.cpp.i
.PHONY : external/AndroidIO.cpp.i

external/AndroidIO.s: external/AndroidIO.cpp.s

.PHONY : external/AndroidIO.s

# target to generate assembly for a file
external/AndroidIO.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/AndroidIO.cpp.s
.PHONY : external/AndroidIO.cpp.s

external/SLB.o: external/SLB.cpp.o

.PHONY : external/SLB.o

# target to build an object file
external/SLB.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/SLB.cpp.o
.PHONY : external/SLB.cpp.o

external/SLB.i: external/SLB.cpp.i

.PHONY : external/SLB.i

# target to preprocess a source file
external/SLB.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/SLB.cpp.i
.PHONY : external/SLB.cpp.i

external/SLB.s: external/SLB.cpp.s

.PHONY : external/SLB.s

# target to generate assembly for a file
external/SLB.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/external/SLB.cpp.s
.PHONY : external/SLB.cpp.s

source/Game.o: source/Game.cpp.o

.PHONY : source/Game.o

# target to build an object file
source/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/Game.cpp.o
.PHONY : source/Game.cpp.o

source/Game.i: source/Game.cpp.i

.PHONY : source/Game.i

# target to preprocess a source file
source/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/Game.cpp.i
.PHONY : source/Game.cpp.i

source/Game.s: source/Game.cpp.s

.PHONY : source/Game.s

# target to generate assembly for a file
source/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/Game.cpp.s
.PHONY : source/Game.cpp.s

source/activities/Activity.o: source/activities/Activity.cpp.o

.PHONY : source/activities/Activity.o

# target to build an object file
source/activities/Activity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/Activity.cpp.o
.PHONY : source/activities/Activity.cpp.o

source/activities/Activity.i: source/activities/Activity.cpp.i

.PHONY : source/activities/Activity.i

# target to preprocess a source file
source/activities/Activity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/Activity.cpp.i
.PHONY : source/activities/Activity.cpp.i

source/activities/Activity.s: source/activities/Activity.cpp.s

.PHONY : source/activities/Activity.s

# target to generate assembly for a file
source/activities/Activity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/Activity.cpp.s
.PHONY : source/activities/Activity.cpp.s

source/activities/BattleActivity.o: source/activities/BattleActivity.cpp.o

.PHONY : source/activities/BattleActivity.o

# target to build an object file
source/activities/BattleActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/BattleActivity.cpp.o
.PHONY : source/activities/BattleActivity.cpp.o

source/activities/BattleActivity.i: source/activities/BattleActivity.cpp.i

.PHONY : source/activities/BattleActivity.i

# target to preprocess a source file
source/activities/BattleActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/BattleActivity.cpp.i
.PHONY : source/activities/BattleActivity.cpp.i

source/activities/BattleActivity.s: source/activities/BattleActivity.cpp.s

.PHONY : source/activities/BattleActivity.s

# target to generate assembly for a file
source/activities/BattleActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/BattleActivity.cpp.s
.PHONY : source/activities/BattleActivity.cpp.s

source/activities/EndActivity.o: source/activities/EndActivity.cpp.o

.PHONY : source/activities/EndActivity.o

# target to build an object file
source/activities/EndActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EndActivity.cpp.o
.PHONY : source/activities/EndActivity.cpp.o

source/activities/EndActivity.i: source/activities/EndActivity.cpp.i

.PHONY : source/activities/EndActivity.i

# target to preprocess a source file
source/activities/EndActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EndActivity.cpp.i
.PHONY : source/activities/EndActivity.cpp.i

source/activities/EndActivity.s: source/activities/EndActivity.cpp.s

.PHONY : source/activities/EndActivity.s

# target to generate assembly for a file
source/activities/EndActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EndActivity.cpp.s
.PHONY : source/activities/EndActivity.cpp.s

source/activities/EquipActivity.o: source/activities/EquipActivity.cpp.o

.PHONY : source/activities/EquipActivity.o

# target to build an object file
source/activities/EquipActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EquipActivity.cpp.o
.PHONY : source/activities/EquipActivity.cpp.o

source/activities/EquipActivity.i: source/activities/EquipActivity.cpp.i

.PHONY : source/activities/EquipActivity.i

# target to preprocess a source file
source/activities/EquipActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EquipActivity.cpp.i
.PHONY : source/activities/EquipActivity.cpp.i

source/activities/EquipActivity.s: source/activities/EquipActivity.cpp.s

.PHONY : source/activities/EquipActivity.s

# target to generate assembly for a file
source/activities/EquipActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/EquipActivity.cpp.s
.PHONY : source/activities/EquipActivity.cpp.s

source/activities/ItemActivity.o: source/activities/ItemActivity.cpp.o

.PHONY : source/activities/ItemActivity.o

# target to build an object file
source/activities/ItemActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/ItemActivity.cpp.o
.PHONY : source/activities/ItemActivity.cpp.o

source/activities/ItemActivity.i: source/activities/ItemActivity.cpp.i

.PHONY : source/activities/ItemActivity.i

# target to preprocess a source file
source/activities/ItemActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/ItemActivity.cpp.i
.PHONY : source/activities/ItemActivity.cpp.i

source/activities/ItemActivity.s: source/activities/ItemActivity.cpp.s

.PHONY : source/activities/ItemActivity.s

# target to generate assembly for a file
source/activities/ItemActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/ItemActivity.cpp.s
.PHONY : source/activities/ItemActivity.cpp.s

source/activities/LuaActivity.o: source/activities/LuaActivity.cpp.o

.PHONY : source/activities/LuaActivity.o

# target to build an object file
source/activities/LuaActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/LuaActivity.cpp.o
.PHONY : source/activities/LuaActivity.cpp.o

source/activities/LuaActivity.i: source/activities/LuaActivity.cpp.i

.PHONY : source/activities/LuaActivity.i

# target to preprocess a source file
source/activities/LuaActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/LuaActivity.cpp.i
.PHONY : source/activities/LuaActivity.cpp.i

source/activities/LuaActivity.s: source/activities/LuaActivity.cpp.s

.PHONY : source/activities/LuaActivity.s

# target to generate assembly for a file
source/activities/LuaActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/LuaActivity.cpp.s
.PHONY : source/activities/LuaActivity.cpp.s

source/activities/MapActivity.o: source/activities/MapActivity.cpp.o

.PHONY : source/activities/MapActivity.o

# target to build an object file
source/activities/MapActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MapActivity.cpp.o
.PHONY : source/activities/MapActivity.cpp.o

source/activities/MapActivity.i: source/activities/MapActivity.cpp.i

.PHONY : source/activities/MapActivity.i

# target to preprocess a source file
source/activities/MapActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MapActivity.cpp.i
.PHONY : source/activities/MapActivity.cpp.i

source/activities/MapActivity.s: source/activities/MapActivity.cpp.s

.PHONY : source/activities/MapActivity.s

# target to generate assembly for a file
source/activities/MapActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MapActivity.cpp.s
.PHONY : source/activities/MapActivity.cpp.s

source/activities/MenuActivity.o: source/activities/MenuActivity.cpp.o

.PHONY : source/activities/MenuActivity.o

# target to build an object file
source/activities/MenuActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MenuActivity.cpp.o
.PHONY : source/activities/MenuActivity.cpp.o

source/activities/MenuActivity.i: source/activities/MenuActivity.cpp.i

.PHONY : source/activities/MenuActivity.i

# target to preprocess a source file
source/activities/MenuActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MenuActivity.cpp.i
.PHONY : source/activities/MenuActivity.cpp.i

source/activities/MenuActivity.s: source/activities/MenuActivity.cpp.s

.PHONY : source/activities/MenuActivity.s

# target to generate assembly for a file
source/activities/MenuActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MenuActivity.cpp.s
.PHONY : source/activities/MenuActivity.cpp.s

source/activities/MessageActivity.o: source/activities/MessageActivity.cpp.o

.PHONY : source/activities/MessageActivity.o

# target to build an object file
source/activities/MessageActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MessageActivity.cpp.o
.PHONY : source/activities/MessageActivity.cpp.o

source/activities/MessageActivity.i: source/activities/MessageActivity.cpp.i

.PHONY : source/activities/MessageActivity.i

# target to preprocess a source file
source/activities/MessageActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MessageActivity.cpp.i
.PHONY : source/activities/MessageActivity.cpp.i

source/activities/MessageActivity.s: source/activities/MessageActivity.cpp.s

.PHONY : source/activities/MessageActivity.s

# target to generate assembly for a file
source/activities/MessageActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/MessageActivity.cpp.s
.PHONY : source/activities/MessageActivity.cpp.s

source/activities/QuestActivity.o: source/activities/QuestActivity.cpp.o

.PHONY : source/activities/QuestActivity.o

# target to build an object file
source/activities/QuestActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/QuestActivity.cpp.o
.PHONY : source/activities/QuestActivity.cpp.o

source/activities/QuestActivity.i: source/activities/QuestActivity.cpp.i

.PHONY : source/activities/QuestActivity.i

# target to preprocess a source file
source/activities/QuestActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/QuestActivity.cpp.i
.PHONY : source/activities/QuestActivity.cpp.i

source/activities/QuestActivity.s: source/activities/QuestActivity.cpp.s

.PHONY : source/activities/QuestActivity.s

# target to generate assembly for a file
source/activities/QuestActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/QuestActivity.cpp.s
.PHONY : source/activities/QuestActivity.cpp.s

source/activities/SettingsActivity.o: source/activities/SettingsActivity.cpp.o

.PHONY : source/activities/SettingsActivity.o

# target to build an object file
source/activities/SettingsActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/SettingsActivity.cpp.o
.PHONY : source/activities/SettingsActivity.cpp.o

source/activities/SettingsActivity.i: source/activities/SettingsActivity.cpp.i

.PHONY : source/activities/SettingsActivity.i

# target to preprocess a source file
source/activities/SettingsActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/SettingsActivity.cpp.i
.PHONY : source/activities/SettingsActivity.cpp.i

source/activities/SettingsActivity.s: source/activities/SettingsActivity.cpp.s

.PHONY : source/activities/SettingsActivity.s

# target to generate assembly for a file
source/activities/SettingsActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/SettingsActivity.cpp.s
.PHONY : source/activities/SettingsActivity.cpp.s

source/activities/TitleActivity.o: source/activities/TitleActivity.cpp.o

.PHONY : source/activities/TitleActivity.o

# target to build an object file
source/activities/TitleActivity.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/TitleActivity.cpp.o
.PHONY : source/activities/TitleActivity.cpp.o

source/activities/TitleActivity.i: source/activities/TitleActivity.cpp.i

.PHONY : source/activities/TitleActivity.i

# target to preprocess a source file
source/activities/TitleActivity.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/TitleActivity.cpp.i
.PHONY : source/activities/TitleActivity.cpp.i

source/activities/TitleActivity.s: source/activities/TitleActivity.cpp.s

.PHONY : source/activities/TitleActivity.s

# target to generate assembly for a file
source/activities/TitleActivity.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/activities/TitleActivity.cpp.s
.PHONY : source/activities/TitleActivity.cpp.s

source/core/Color.o: source/core/Color.cpp.o

.PHONY : source/core/Color.o

# target to build an object file
source/core/Color.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Color.cpp.o
.PHONY : source/core/Color.cpp.o

source/core/Color.i: source/core/Color.cpp.i

.PHONY : source/core/Color.i

# target to preprocess a source file
source/core/Color.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Color.cpp.i
.PHONY : source/core/Color.cpp.i

source/core/Color.s: source/core/Color.cpp.s

.PHONY : source/core/Color.s

# target to generate assembly for a file
source/core/Color.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Color.cpp.s
.PHONY : source/core/Color.cpp.s

source/core/LuaHandler.o: source/core/LuaHandler.cpp.o

.PHONY : source/core/LuaHandler.o

# target to build an object file
source/core/LuaHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/LuaHandler.cpp.o
.PHONY : source/core/LuaHandler.cpp.o

source/core/LuaHandler.i: source/core/LuaHandler.cpp.i

.PHONY : source/core/LuaHandler.i

# target to preprocess a source file
source/core/LuaHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/LuaHandler.cpp.i
.PHONY : source/core/LuaHandler.cpp.i

source/core/LuaHandler.s: source/core/LuaHandler.cpp.s

.PHONY : source/core/LuaHandler.s

# target to generate assembly for a file
source/core/LuaHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/LuaHandler.cpp.s
.PHONY : source/core/LuaHandler.cpp.s

source/core/Parameter.o: source/core/Parameter.cpp.o

.PHONY : source/core/Parameter.o

# target to build an object file
source/core/Parameter.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Parameter.cpp.o
.PHONY : source/core/Parameter.cpp.o

source/core/Parameter.i: source/core/Parameter.cpp.i

.PHONY : source/core/Parameter.i

# target to preprocess a source file
source/core/Parameter.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Parameter.cpp.i
.PHONY : source/core/Parameter.cpp.i

source/core/Parameter.s: source/core/Parameter.cpp.s

.PHONY : source/core/Parameter.s

# target to generate assembly for a file
source/core/Parameter.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Parameter.cpp.s
.PHONY : source/core/Parameter.cpp.s

source/core/SDLManager.o: source/core/SDLManager.cpp.o

.PHONY : source/core/SDLManager.o

# target to build an object file
source/core/SDLManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/SDLManager.cpp.o
.PHONY : source/core/SDLManager.cpp.o

source/core/SDLManager.i: source/core/SDLManager.cpp.i

.PHONY : source/core/SDLManager.i

# target to preprocess a source file
source/core/SDLManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/SDLManager.cpp.i
.PHONY : source/core/SDLManager.cpp.i

source/core/SDLManager.s: source/core/SDLManager.cpp.s

.PHONY : source/core/SDLManager.s

# target to generate assembly for a file
source/core/SDLManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/SDLManager.cpp.s
.PHONY : source/core/SDLManager.cpp.s

source/core/Sound.o: source/core/Sound.cpp.o

.PHONY : source/core/Sound.o

# target to build an object file
source/core/Sound.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Sound.cpp.o
.PHONY : source/core/Sound.cpp.o

source/core/Sound.i: source/core/Sound.cpp.i

.PHONY : source/core/Sound.i

# target to preprocess a source file
source/core/Sound.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Sound.cpp.i
.PHONY : source/core/Sound.cpp.i

source/core/Sound.s: source/core/Sound.cpp.s

.PHONY : source/core/Sound.s

# target to generate assembly for a file
source/core/Sound.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/Sound.cpp.s
.PHONY : source/core/Sound.cpp.s

source/core/TimeManager.o: source/core/TimeManager.cpp.o

.PHONY : source/core/TimeManager.o

# target to build an object file
source/core/TimeManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/TimeManager.cpp.o
.PHONY : source/core/TimeManager.cpp.o

source/core/TimeManager.i: source/core/TimeManager.cpp.i

.PHONY : source/core/TimeManager.i

# target to preprocess a source file
source/core/TimeManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/TimeManager.cpp.i
.PHONY : source/core/TimeManager.cpp.i

source/core/TimeManager.s: source/core/TimeManager.cpp.s

.PHONY : source/core/TimeManager.s

# target to generate assembly for a file
source/core/TimeManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/TimeManager.cpp.s
.PHONY : source/core/TimeManager.cpp.s

source/core/XMLFile.o: source/core/XMLFile.cpp.o

.PHONY : source/core/XMLFile.o

# target to build an object file
source/core/XMLFile.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/XMLFile.cpp.o
.PHONY : source/core/XMLFile.cpp.o

source/core/XMLFile.i: source/core/XMLFile.cpp.i

.PHONY : source/core/XMLFile.i

# target to preprocess a source file
source/core/XMLFile.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/XMLFile.cpp.i
.PHONY : source/core/XMLFile.cpp.i

source/core/XMLFile.s: source/core/XMLFile.cpp.s

.PHONY : source/core/XMLFile.s

# target to generate assembly for a file
source/core/XMLFile.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/core/XMLFile.cpp.s
.PHONY : source/core/XMLFile.cpp.s

source/display/Animation.o: source/display/Animation.cpp.o

.PHONY : source/display/Animation.o

# target to build an object file
source/display/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Animation.cpp.o
.PHONY : source/display/Animation.cpp.o

source/display/Animation.i: source/display/Animation.cpp.i

.PHONY : source/display/Animation.i

# target to preprocess a source file
source/display/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Animation.cpp.i
.PHONY : source/display/Animation.cpp.i

source/display/Animation.s: source/display/Animation.cpp.s

.PHONY : source/display/Animation.s

# target to generate assembly for a file
source/display/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Animation.cpp.s
.PHONY : source/display/Animation.cpp.s

source/display/AnimationManager.o: source/display/AnimationManager.cpp.o

.PHONY : source/display/AnimationManager.o

# target to build an object file
source/display/AnimationManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/AnimationManager.cpp.o
.PHONY : source/display/AnimationManager.cpp.o

source/display/AnimationManager.i: source/display/AnimationManager.cpp.i

.PHONY : source/display/AnimationManager.i

# target to preprocess a source file
source/display/AnimationManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/AnimationManager.cpp.i
.PHONY : source/display/AnimationManager.cpp.i

source/display/AnimationManager.s: source/display/AnimationManager.cpp.s

.PHONY : source/display/AnimationManager.s

# target to generate assembly for a file
source/display/AnimationManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/AnimationManager.cpp.s
.PHONY : source/display/AnimationManager.cpp.s

source/display/Font.o: source/display/Font.cpp.o

.PHONY : source/display/Font.o

# target to build an object file
source/display/Font.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Font.cpp.o
.PHONY : source/display/Font.cpp.o

source/display/Font.i: source/display/Font.cpp.i

.PHONY : source/display/Font.i

# target to preprocess a source file
source/display/Font.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Font.cpp.i
.PHONY : source/display/Font.cpp.i

source/display/Font.s: source/display/Font.cpp.s

.PHONY : source/display/Font.s

# target to generate assembly for a file
source/display/Font.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Font.cpp.s
.PHONY : source/display/Font.cpp.s

source/display/GameWindow.o: source/display/GameWindow.cpp.o

.PHONY : source/display/GameWindow.o

# target to build an object file
source/display/GameWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/GameWindow.cpp.o
.PHONY : source/display/GameWindow.cpp.o

source/display/GameWindow.i: source/display/GameWindow.cpp.i

.PHONY : source/display/GameWindow.i

# target to preprocess a source file
source/display/GameWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/GameWindow.cpp.i
.PHONY : source/display/GameWindow.cpp.i

source/display/GameWindow.s: source/display/GameWindow.cpp.s

.PHONY : source/display/GameWindow.s

# target to generate assembly for a file
source/display/GameWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/GameWindow.cpp.s
.PHONY : source/display/GameWindow.cpp.s

source/display/Image.o: source/display/Image.cpp.o

.PHONY : source/display/Image.o

# target to build an object file
source/display/Image.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Image.cpp.o
.PHONY : source/display/Image.cpp.o

source/display/Image.i: source/display/Image.cpp.i

.PHONY : source/display/Image.i

# target to preprocess a source file
source/display/Image.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Image.cpp.i
.PHONY : source/display/Image.cpp.i

source/display/Image.s: source/display/Image.cpp.s

.PHONY : source/display/Image.s

# target to generate assembly for a file
source/display/Image.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Image.cpp.s
.PHONY : source/display/Image.cpp.s

source/display/Interface.o: source/display/Interface.cpp.o

.PHONY : source/display/Interface.o

# target to build an object file
source/display/Interface.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Interface.cpp.o
.PHONY : source/display/Interface.cpp.o

source/display/Interface.i: source/display/Interface.cpp.i

.PHONY : source/display/Interface.i

# target to preprocess a source file
source/display/Interface.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Interface.cpp.i
.PHONY : source/display/Interface.cpp.i

source/display/Interface.s: source/display/Interface.cpp.s

.PHONY : source/display/Interface.s

# target to generate assembly for a file
source/display/Interface.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Interface.cpp.s
.PHONY : source/display/Interface.cpp.s

source/display/Map.o: source/display/Map.cpp.o

.PHONY : source/display/Map.o

# target to build an object file
source/display/Map.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Map.cpp.o
.PHONY : source/display/Map.cpp.o

source/display/Map.i: source/display/Map.cpp.i

.PHONY : source/display/Map.i

# target to preprocess a source file
source/display/Map.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Map.cpp.i
.PHONY : source/display/Map.cpp.i

source/display/Map.s: source/display/Map.cpp.s

.PHONY : source/display/Map.s

# target to generate assembly for a file
source/display/Map.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Map.cpp.s
.PHONY : source/display/Map.cpp.s

source/display/MapManager.o: source/display/MapManager.cpp.o

.PHONY : source/display/MapManager.o

# target to build an object file
source/display/MapManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/MapManager.cpp.o
.PHONY : source/display/MapManager.cpp.o

source/display/MapManager.i: source/display/MapManager.cpp.i

.PHONY : source/display/MapManager.i

# target to preprocess a source file
source/display/MapManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/MapManager.cpp.i
.PHONY : source/display/MapManager.cpp.i

source/display/MapManager.s: source/display/MapManager.cpp.s

.PHONY : source/display/MapManager.s

# target to generate assembly for a file
source/display/MapManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/MapManager.cpp.s
.PHONY : source/display/MapManager.cpp.s

source/display/Sprite.o: source/display/Sprite.cpp.o

.PHONY : source/display/Sprite.o

# target to build an object file
source/display/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Sprite.cpp.o
.PHONY : source/display/Sprite.cpp.o

source/display/Sprite.i: source/display/Sprite.cpp.i

.PHONY : source/display/Sprite.i

# target to preprocess a source file
source/display/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Sprite.cpp.i
.PHONY : source/display/Sprite.cpp.i

source/display/Sprite.s: source/display/Sprite.cpp.s

.PHONY : source/display/Sprite.s

# target to generate assembly for a file
source/display/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Sprite.cpp.s
.PHONY : source/display/Sprite.cpp.s

source/display/SpriteAnimationManager.o: source/display/SpriteAnimationManager.cpp.o

.PHONY : source/display/SpriteAnimationManager.o

# target to build an object file
source/display/SpriteAnimationManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/SpriteAnimationManager.cpp.o
.PHONY : source/display/SpriteAnimationManager.cpp.o

source/display/SpriteAnimationManager.i: source/display/SpriteAnimationManager.cpp.i

.PHONY : source/display/SpriteAnimationManager.i

# target to preprocess a source file
source/display/SpriteAnimationManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/SpriteAnimationManager.cpp.i
.PHONY : source/display/SpriteAnimationManager.cpp.i

source/display/SpriteAnimationManager.s: source/display/SpriteAnimationManager.cpp.s

.PHONY : source/display/SpriteAnimationManager.s

# target to generate assembly for a file
source/display/SpriteAnimationManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/SpriteAnimationManager.cpp.s
.PHONY : source/display/SpriteAnimationManager.cpp.s

source/display/Timer.o: source/display/Timer.cpp.o

.PHONY : source/display/Timer.o

# target to build an object file
source/display/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Timer.cpp.o
.PHONY : source/display/Timer.cpp.o

source/display/Timer.i: source/display/Timer.cpp.i

.PHONY : source/display/Timer.i

# target to preprocess a source file
source/display/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Timer.cpp.i
.PHONY : source/display/Timer.cpp.i

source/display/Timer.s: source/display/Timer.cpp.s

.PHONY : source/display/Timer.s

# target to generate assembly for a file
source/display/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/display/Timer.cpp.s
.PHONY : source/display/Timer.cpp.s

source/entities/Actor.o: source/entities/Actor.cpp.o

.PHONY : source/entities/Actor.o

# target to build an object file
source/entities/Actor.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Actor.cpp.o
.PHONY : source/entities/Actor.cpp.o

source/entities/Actor.i: source/entities/Actor.cpp.i

.PHONY : source/entities/Actor.i

# target to preprocess a source file
source/entities/Actor.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Actor.cpp.i
.PHONY : source/entities/Actor.cpp.i

source/entities/Actor.s: source/entities/Actor.cpp.s

.PHONY : source/entities/Actor.s

# target to generate assembly for a file
source/entities/Actor.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Actor.cpp.s
.PHONY : source/entities/Actor.cpp.s

source/entities/Battler.o: source/entities/Battler.cpp.o

.PHONY : source/entities/Battler.o

# target to build an object file
source/entities/Battler.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Battler.cpp.o
.PHONY : source/entities/Battler.cpp.o

source/entities/Battler.i: source/entities/Battler.cpp.i

.PHONY : source/entities/Battler.i

# target to preprocess a source file
source/entities/Battler.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Battler.cpp.i
.PHONY : source/entities/Battler.cpp.i

source/entities/Battler.s: source/entities/Battler.cpp.s

.PHONY : source/entities/Battler.s

# target to generate assembly for a file
source/entities/Battler.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Battler.cpp.s
.PHONY : source/entities/Battler.cpp.s

source/entities/Character.o: source/entities/Character.cpp.o

.PHONY : source/entities/Character.o

# target to build an object file
source/entities/Character.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Character.cpp.o
.PHONY : source/entities/Character.cpp.o

source/entities/Character.i: source/entities/Character.cpp.i

.PHONY : source/entities/Character.i

# target to preprocess a source file
source/entities/Character.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Character.cpp.i
.PHONY : source/entities/Character.cpp.i

source/entities/Character.s: source/entities/Character.cpp.s

.PHONY : source/entities/Character.s

# target to generate assembly for a file
source/entities/Character.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Character.cpp.s
.PHONY : source/entities/Character.cpp.s

source/entities/Enemy.o: source/entities/Enemy.cpp.o

.PHONY : source/entities/Enemy.o

# target to build an object file
source/entities/Enemy.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Enemy.cpp.o
.PHONY : source/entities/Enemy.cpp.o

source/entities/Enemy.i: source/entities/Enemy.cpp.i

.PHONY : source/entities/Enemy.i

# target to preprocess a source file
source/entities/Enemy.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Enemy.cpp.i
.PHONY : source/entities/Enemy.cpp.i

source/entities/Enemy.s: source/entities/Enemy.cpp.s

.PHONY : source/entities/Enemy.s

# target to generate assembly for a file
source/entities/Enemy.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Enemy.cpp.s
.PHONY : source/entities/Enemy.cpp.s

source/entities/Player.o: source/entities/Player.cpp.o

.PHONY : source/entities/Player.o

# target to build an object file
source/entities/Player.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Player.cpp.o
.PHONY : source/entities/Player.cpp.o

source/entities/Player.i: source/entities/Player.cpp.i

.PHONY : source/entities/Player.i

# target to preprocess a source file
source/entities/Player.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Player.cpp.i
.PHONY : source/entities/Player.cpp.i

source/entities/Player.s: source/entities/Player.cpp.s

.PHONY : source/entities/Player.s

# target to generate assembly for a file
source/entities/Player.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/entities/Player.cpp.s
.PHONY : source/entities/Player.cpp.s

source/events/Event.o: source/events/Event.cpp.o

.PHONY : source/events/Event.o

# target to build an object file
source/events/Event.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/Event.cpp.o
.PHONY : source/events/Event.cpp.o

source/events/Event.i: source/events/Event.cpp.i

.PHONY : source/events/Event.i

# target to preprocess a source file
source/events/Event.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/Event.cpp.i
.PHONY : source/events/Event.cpp.i

source/events/Event.s: source/events/Event.cpp.s

.PHONY : source/events/Event.s

# target to generate assembly for a file
source/events/Event.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/Event.cpp.s
.PHONY : source/events/Event.cpp.s

source/events/EventAction.o: source/events/EventAction.cpp.o

.PHONY : source/events/EventAction.o

# target to build an object file
source/events/EventAction.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventAction.cpp.o
.PHONY : source/events/EventAction.cpp.o

source/events/EventAction.i: source/events/EventAction.cpp.i

.PHONY : source/events/EventAction.i

# target to preprocess a source file
source/events/EventAction.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventAction.cpp.i
.PHONY : source/events/EventAction.cpp.i

source/events/EventAction.s: source/events/EventAction.cpp.s

.PHONY : source/events/EventAction.s

# target to generate assembly for a file
source/events/EventAction.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventAction.cpp.s
.PHONY : source/events/EventAction.cpp.s

source/events/EventInterpreter.o: source/events/EventInterpreter.cpp.o

.PHONY : source/events/EventInterpreter.o

# target to build an object file
source/events/EventInterpreter.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventInterpreter.cpp.o
.PHONY : source/events/EventInterpreter.cpp.o

source/events/EventInterpreter.i: source/events/EventInterpreter.cpp.i

.PHONY : source/events/EventInterpreter.i

# target to preprocess a source file
source/events/EventInterpreter.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventInterpreter.cpp.i
.PHONY : source/events/EventInterpreter.cpp.i

source/events/EventInterpreter.s: source/events/EventInterpreter.cpp.s

.PHONY : source/events/EventInterpreter.s

# target to generate assembly for a file
source/events/EventInterpreter.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventInterpreter.cpp.s
.PHONY : source/events/EventInterpreter.cpp.s

source/events/EventListener.o: source/events/EventListener.cpp.o

.PHONY : source/events/EventListener.o

# target to build an object file
source/events/EventListener.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventListener.cpp.o
.PHONY : source/events/EventListener.cpp.o

source/events/EventListener.i: source/events/EventListener.cpp.i

.PHONY : source/events/EventListener.i

# target to preprocess a source file
source/events/EventListener.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventListener.cpp.i
.PHONY : source/events/EventListener.cpp.i

source/events/EventListener.s: source/events/EventListener.cpp.s

.PHONY : source/events/EventListener.s

# target to generate assembly for a file
source/events/EventListener.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/events/EventListener.cpp.s
.PHONY : source/events/EventListener.cpp.s

source/main.o: source/main.cpp.o

.PHONY : source/main.o

# target to build an object file
source/main.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/main.cpp.o
.PHONY : source/main.cpp.o

source/main.i: source/main.cpp.i

.PHONY : source/main.i

# target to preprocess a source file
source/main.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/main.cpp.i
.PHONY : source/main.cpp.i

source/main.s: source/main.cpp.s

.PHONY : source/main.s

# target to generate assembly for a file
source/main.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/main.cpp.s
.PHONY : source/main.cpp.s

source/managers/ActivityManager.o: source/managers/ActivityManager.cpp.o

.PHONY : source/managers/ActivityManager.o

# target to build an object file
source/managers/ActivityManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ActivityManager.cpp.o
.PHONY : source/managers/ActivityManager.cpp.o

source/managers/ActivityManager.i: source/managers/ActivityManager.cpp.i

.PHONY : source/managers/ActivityManager.i

# target to preprocess a source file
source/managers/ActivityManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ActivityManager.cpp.i
.PHONY : source/managers/ActivityManager.cpp.i

source/managers/ActivityManager.s: source/managers/ActivityManager.cpp.s

.PHONY : source/managers/ActivityManager.s

# target to generate assembly for a file
source/managers/ActivityManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ActivityManager.cpp.s
.PHONY : source/managers/ActivityManager.cpp.s

source/managers/BattlerManager.o: source/managers/BattlerManager.cpp.o

.PHONY : source/managers/BattlerManager.o

# target to build an object file
source/managers/BattlerManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/BattlerManager.cpp.o
.PHONY : source/managers/BattlerManager.cpp.o

source/managers/BattlerManager.i: source/managers/BattlerManager.cpp.i

.PHONY : source/managers/BattlerManager.i

# target to preprocess a source file
source/managers/BattlerManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/BattlerManager.cpp.i
.PHONY : source/managers/BattlerManager.cpp.i

source/managers/BattlerManager.s: source/managers/BattlerManager.cpp.s

.PHONY : source/managers/BattlerManager.s

# target to generate assembly for a file
source/managers/BattlerManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/BattlerManager.cpp.s
.PHONY : source/managers/BattlerManager.cpp.s

source/managers/CharacterManager.o: source/managers/CharacterManager.cpp.o

.PHONY : source/managers/CharacterManager.o

# target to build an object file
source/managers/CharacterManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/CharacterManager.cpp.o
.PHONY : source/managers/CharacterManager.cpp.o

source/managers/CharacterManager.i: source/managers/CharacterManager.cpp.i

.PHONY : source/managers/CharacterManager.i

# target to preprocess a source file
source/managers/CharacterManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/CharacterManager.cpp.i
.PHONY : source/managers/CharacterManager.cpp.i

source/managers/CharacterManager.s: source/managers/CharacterManager.cpp.s

.PHONY : source/managers/CharacterManager.s

# target to generate assembly for a file
source/managers/CharacterManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/CharacterManager.cpp.s
.PHONY : source/managers/CharacterManager.cpp.s

source/managers/EventManager.o: source/managers/EventManager.cpp.o

.PHONY : source/managers/EventManager.o

# target to build an object file
source/managers/EventManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/EventManager.cpp.o
.PHONY : source/managers/EventManager.cpp.o

source/managers/EventManager.i: source/managers/EventManager.cpp.i

.PHONY : source/managers/EventManager.i

# target to preprocess a source file
source/managers/EventManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/EventManager.cpp.i
.PHONY : source/managers/EventManager.cpp.i

source/managers/EventManager.s: source/managers/EventManager.cpp.s

.PHONY : source/managers/EventManager.s

# target to generate assembly for a file
source/managers/EventManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/EventManager.cpp.s
.PHONY : source/managers/EventManager.cpp.s

source/managers/ItemManager.o: source/managers/ItemManager.cpp.o

.PHONY : source/managers/ItemManager.o

# target to build an object file
source/managers/ItemManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ItemManager.cpp.o
.PHONY : source/managers/ItemManager.cpp.o

source/managers/ItemManager.i: source/managers/ItemManager.cpp.i

.PHONY : source/managers/ItemManager.i

# target to preprocess a source file
source/managers/ItemManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ItemManager.cpp.i
.PHONY : source/managers/ItemManager.cpp.i

source/managers/ItemManager.s: source/managers/ItemManager.cpp.s

.PHONY : source/managers/ItemManager.s

# target to generate assembly for a file
source/managers/ItemManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/ItemManager.cpp.s
.PHONY : source/managers/ItemManager.cpp.s

source/managers/LanguageManager.o: source/managers/LanguageManager.cpp.o

.PHONY : source/managers/LanguageManager.o

# target to build an object file
source/managers/LanguageManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/LanguageManager.cpp.o
.PHONY : source/managers/LanguageManager.cpp.o

source/managers/LanguageManager.i: source/managers/LanguageManager.cpp.i

.PHONY : source/managers/LanguageManager.i

# target to preprocess a source file
source/managers/LanguageManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/LanguageManager.cpp.i
.PHONY : source/managers/LanguageManager.cpp.i

source/managers/LanguageManager.s: source/managers/LanguageManager.cpp.s

.PHONY : source/managers/LanguageManager.s

# target to generate assembly for a file
source/managers/LanguageManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/LanguageManager.cpp.s
.PHONY : source/managers/LanguageManager.cpp.s

source/managers/QuestManager.o: source/managers/QuestManager.cpp.o

.PHONY : source/managers/QuestManager.o

# target to build an object file
source/managers/QuestManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/QuestManager.cpp.o
.PHONY : source/managers/QuestManager.cpp.o

source/managers/QuestManager.i: source/managers/QuestManager.cpp.i

.PHONY : source/managers/QuestManager.i

# target to preprocess a source file
source/managers/QuestManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/QuestManager.cpp.i
.PHONY : source/managers/QuestManager.cpp.i

source/managers/QuestManager.s: source/managers/QuestManager.cpp.s

.PHONY : source/managers/QuestManager.s

# target to generate assembly for a file
source/managers/QuestManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/QuestManager.cpp.s
.PHONY : source/managers/QuestManager.cpp.s

source/managers/SaveManager.o: source/managers/SaveManager.cpp.o

.PHONY : source/managers/SaveManager.o

# target to build an object file
source/managers/SaveManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/SaveManager.cpp.o
.PHONY : source/managers/SaveManager.cpp.o

source/managers/SaveManager.i: source/managers/SaveManager.cpp.i

.PHONY : source/managers/SaveManager.i

# target to preprocess a source file
source/managers/SaveManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/SaveManager.cpp.i
.PHONY : source/managers/SaveManager.cpp.i

source/managers/SaveManager.s: source/managers/SaveManager.cpp.s

.PHONY : source/managers/SaveManager.s

# target to generate assembly for a file
source/managers/SaveManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/SaveManager.cpp.s
.PHONY : source/managers/SaveManager.cpp.s

source/managers/TroopManager.o: source/managers/TroopManager.cpp.o

.PHONY : source/managers/TroopManager.o

# target to build an object file
source/managers/TroopManager.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/TroopManager.cpp.o
.PHONY : source/managers/TroopManager.cpp.o

source/managers/TroopManager.i: source/managers/TroopManager.cpp.i

.PHONY : source/managers/TroopManager.i

# target to preprocess a source file
source/managers/TroopManager.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/TroopManager.cpp.i
.PHONY : source/managers/TroopManager.cpp.i

source/managers/TroopManager.s: source/managers/TroopManager.cpp.s

.PHONY : source/managers/TroopManager.s

# target to generate assembly for a file
source/managers/TroopManager.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/managers/TroopManager.cpp.s
.PHONY : source/managers/TroopManager.cpp.s

source/objects/Armor.o: source/objects/Armor.cpp.o

.PHONY : source/objects/Armor.o

# target to build an object file
source/objects/Armor.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Armor.cpp.o
.PHONY : source/objects/Armor.cpp.o

source/objects/Armor.i: source/objects/Armor.cpp.i

.PHONY : source/objects/Armor.i

# target to preprocess a source file
source/objects/Armor.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Armor.cpp.i
.PHONY : source/objects/Armor.cpp.i

source/objects/Armor.s: source/objects/Armor.cpp.s

.PHONY : source/objects/Armor.s

# target to generate assembly for a file
source/objects/Armor.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Armor.cpp.s
.PHONY : source/objects/Armor.cpp.s

source/objects/Battle.o: source/objects/Battle.cpp.o

.PHONY : source/objects/Battle.o

# target to build an object file
source/objects/Battle.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Battle.cpp.o
.PHONY : source/objects/Battle.cpp.o

source/objects/Battle.i: source/objects/Battle.cpp.i

.PHONY : source/objects/Battle.i

# target to preprocess a source file
source/objects/Battle.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Battle.cpp.i
.PHONY : source/objects/Battle.cpp.i

source/objects/Battle.s: source/objects/Battle.cpp.s

.PHONY : source/objects/Battle.s

# target to generate assembly for a file
source/objects/Battle.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Battle.cpp.s
.PHONY : source/objects/Battle.cpp.s

source/objects/BattleAction.o: source/objects/BattleAction.cpp.o

.PHONY : source/objects/BattleAction.o

# target to build an object file
source/objects/BattleAction.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/BattleAction.cpp.o
.PHONY : source/objects/BattleAction.cpp.o

source/objects/BattleAction.i: source/objects/BattleAction.cpp.i

.PHONY : source/objects/BattleAction.i

# target to preprocess a source file
source/objects/BattleAction.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/BattleAction.cpp.i
.PHONY : source/objects/BattleAction.cpp.i

source/objects/BattleAction.s: source/objects/BattleAction.cpp.s

.PHONY : source/objects/BattleAction.s

# target to generate assembly for a file
source/objects/BattleAction.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/BattleAction.cpp.s
.PHONY : source/objects/BattleAction.cpp.s

source/objects/Equipment.o: source/objects/Equipment.cpp.o

.PHONY : source/objects/Equipment.o

# target to build an object file
source/objects/Equipment.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Equipment.cpp.o
.PHONY : source/objects/Equipment.cpp.o

source/objects/Equipment.i: source/objects/Equipment.cpp.i

.PHONY : source/objects/Equipment.i

# target to preprocess a source file
source/objects/Equipment.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Equipment.cpp.i
.PHONY : source/objects/Equipment.cpp.i

source/objects/Equipment.s: source/objects/Equipment.cpp.s

.PHONY : source/objects/Equipment.s

# target to generate assembly for a file
source/objects/Equipment.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Equipment.cpp.s
.PHONY : source/objects/Equipment.cpp.s

source/objects/Inventory.o: source/objects/Inventory.cpp.o

.PHONY : source/objects/Inventory.o

# target to build an object file
source/objects/Inventory.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Inventory.cpp.o
.PHONY : source/objects/Inventory.cpp.o

source/objects/Inventory.i: source/objects/Inventory.cpp.i

.PHONY : source/objects/Inventory.i

# target to preprocess a source file
source/objects/Inventory.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Inventory.cpp.i
.PHONY : source/objects/Inventory.cpp.i

source/objects/Inventory.s: source/objects/Inventory.cpp.s

.PHONY : source/objects/Inventory.s

# target to generate assembly for a file
source/objects/Inventory.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Inventory.cpp.s
.PHONY : source/objects/Inventory.cpp.s

source/objects/Item.o: source/objects/Item.cpp.o

.PHONY : source/objects/Item.o

# target to build an object file
source/objects/Item.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Item.cpp.o
.PHONY : source/objects/Item.cpp.o

source/objects/Item.i: source/objects/Item.cpp.i

.PHONY : source/objects/Item.i

# target to preprocess a source file
source/objects/Item.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Item.cpp.i
.PHONY : source/objects/Item.cpp.i

source/objects/Item.s: source/objects/Item.cpp.s

.PHONY : source/objects/Item.s

# target to generate assembly for a file
source/objects/Item.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Item.cpp.s
.PHONY : source/objects/Item.cpp.s

source/objects/Keyboard.o: source/objects/Keyboard.cpp.o

.PHONY : source/objects/Keyboard.o

# target to build an object file
source/objects/Keyboard.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Keyboard.cpp.o
.PHONY : source/objects/Keyboard.cpp.o

source/objects/Keyboard.i: source/objects/Keyboard.cpp.i

.PHONY : source/objects/Keyboard.i

# target to preprocess a source file
source/objects/Keyboard.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Keyboard.cpp.i
.PHONY : source/objects/Keyboard.cpp.i

source/objects/Keyboard.s: source/objects/Keyboard.cpp.s

.PHONY : source/objects/Keyboard.s

# target to generate assembly for a file
source/objects/Keyboard.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Keyboard.cpp.s
.PHONY : source/objects/Keyboard.cpp.s

source/objects/Skill.o: source/objects/Skill.cpp.o

.PHONY : source/objects/Skill.o

# target to build an object file
source/objects/Skill.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Skill.cpp.o
.PHONY : source/objects/Skill.cpp.o

source/objects/Skill.i: source/objects/Skill.cpp.i

.PHONY : source/objects/Skill.i

# target to preprocess a source file
source/objects/Skill.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Skill.cpp.i
.PHONY : source/objects/Skill.cpp.i

source/objects/Skill.s: source/objects/Skill.cpp.s

.PHONY : source/objects/Skill.s

# target to generate assembly for a file
source/objects/Skill.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Skill.cpp.s
.PHONY : source/objects/Skill.cpp.s

source/objects/Troop.o: source/objects/Troop.cpp.o

.PHONY : source/objects/Troop.o

# target to build an object file
source/objects/Troop.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Troop.cpp.o
.PHONY : source/objects/Troop.cpp.o

source/objects/Troop.i: source/objects/Troop.cpp.i

.PHONY : source/objects/Troop.i

# target to preprocess a source file
source/objects/Troop.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Troop.cpp.i
.PHONY : source/objects/Troop.cpp.i

source/objects/Troop.s: source/objects/Troop.cpp.s

.PHONY : source/objects/Troop.s

# target to generate assembly for a file
source/objects/Troop.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Troop.cpp.s
.PHONY : source/objects/Troop.cpp.s

source/objects/Weapon.o: source/objects/Weapon.cpp.o

.PHONY : source/objects/Weapon.o

# target to build an object file
source/objects/Weapon.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Weapon.cpp.o
.PHONY : source/objects/Weapon.cpp.o

source/objects/Weapon.i: source/objects/Weapon.cpp.i

.PHONY : source/objects/Weapon.i

# target to preprocess a source file
source/objects/Weapon.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Weapon.cpp.i
.PHONY : source/objects/Weapon.cpp.i

source/objects/Weapon.s: source/objects/Weapon.cpp.s

.PHONY : source/objects/Weapon.s

# target to generate assembly for a file
source/objects/Weapon.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/objects/Weapon.cpp.s
.PHONY : source/objects/Weapon.cpp.s

source/quests/Quest.o: source/quests/Quest.cpp.o

.PHONY : source/quests/Quest.o

# target to build an object file
source/quests/Quest.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/Quest.cpp.o
.PHONY : source/quests/Quest.cpp.o

source/quests/Quest.i: source/quests/Quest.cpp.i

.PHONY : source/quests/Quest.i

# target to preprocess a source file
source/quests/Quest.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/Quest.cpp.i
.PHONY : source/quests/Quest.cpp.i

source/quests/Quest.s: source/quests/Quest.cpp.s

.PHONY : source/quests/Quest.s

# target to generate assembly for a file
source/quests/Quest.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/Quest.cpp.s
.PHONY : source/quests/Quest.cpp.s

source/quests/QuestObjective.o: source/quests/QuestObjective.cpp.o

.PHONY : source/quests/QuestObjective.o

# target to build an object file
source/quests/QuestObjective.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/QuestObjective.cpp.o
.PHONY : source/quests/QuestObjective.cpp.o

source/quests/QuestObjective.i: source/quests/QuestObjective.cpp.i

.PHONY : source/quests/QuestObjective.i

# target to preprocess a source file
source/quests/QuestObjective.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/QuestObjective.cpp.i
.PHONY : source/quests/QuestObjective.cpp.i

source/quests/QuestObjective.s: source/quests/QuestObjective.cpp.s

.PHONY : source/quests/QuestObjective.s

# target to generate assembly for a file
source/quests/QuestObjective.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/quests/QuestObjective.cpp.s
.PHONY : source/quests/QuestObjective.cpp.s

source/windows/ActorChoiceWindow.o: source/windows/ActorChoiceWindow.cpp.o

.PHONY : source/windows/ActorChoiceWindow.o

# target to build an object file
source/windows/ActorChoiceWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorChoiceWindow.cpp.o
.PHONY : source/windows/ActorChoiceWindow.cpp.o

source/windows/ActorChoiceWindow.i: source/windows/ActorChoiceWindow.cpp.i

.PHONY : source/windows/ActorChoiceWindow.i

# target to preprocess a source file
source/windows/ActorChoiceWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorChoiceWindow.cpp.i
.PHONY : source/windows/ActorChoiceWindow.cpp.i

source/windows/ActorChoiceWindow.s: source/windows/ActorChoiceWindow.cpp.s

.PHONY : source/windows/ActorChoiceWindow.s

# target to generate assembly for a file
source/windows/ActorChoiceWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorChoiceWindow.cpp.s
.PHONY : source/windows/ActorChoiceWindow.cpp.s

source/windows/ActorStatsWindow.o: source/windows/ActorStatsWindow.cpp.o

.PHONY : source/windows/ActorStatsWindow.o

# target to build an object file
source/windows/ActorStatsWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorStatsWindow.cpp.o
.PHONY : source/windows/ActorStatsWindow.cpp.o

source/windows/ActorStatsWindow.i: source/windows/ActorStatsWindow.cpp.i

.PHONY : source/windows/ActorStatsWindow.i

# target to preprocess a source file
source/windows/ActorStatsWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorStatsWindow.cpp.i
.PHONY : source/windows/ActorStatsWindow.cpp.i

source/windows/ActorStatsWindow.s: source/windows/ActorStatsWindow.cpp.s

.PHONY : source/windows/ActorStatsWindow.s

# target to generate assembly for a file
source/windows/ActorStatsWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ActorStatsWindow.cpp.s
.PHONY : source/windows/ActorStatsWindow.cpp.s

source/windows/BattleActionWindow.o: source/windows/BattleActionWindow.cpp.o

.PHONY : source/windows/BattleActionWindow.o

# target to build an object file
source/windows/BattleActionWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleActionWindow.cpp.o
.PHONY : source/windows/BattleActionWindow.cpp.o

source/windows/BattleActionWindow.i: source/windows/BattleActionWindow.cpp.i

.PHONY : source/windows/BattleActionWindow.i

# target to preprocess a source file
source/windows/BattleActionWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleActionWindow.cpp.i
.PHONY : source/windows/BattleActionWindow.cpp.i

source/windows/BattleActionWindow.s: source/windows/BattleActionWindow.cpp.s

.PHONY : source/windows/BattleActionWindow.s

# target to generate assembly for a file
source/windows/BattleActionWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleActionWindow.cpp.s
.PHONY : source/windows/BattleActionWindow.cpp.s

source/windows/BattleChoiceWindow.o: source/windows/BattleChoiceWindow.cpp.o

.PHONY : source/windows/BattleChoiceWindow.o

# target to build an object file
source/windows/BattleChoiceWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleChoiceWindow.cpp.o
.PHONY : source/windows/BattleChoiceWindow.cpp.o

source/windows/BattleChoiceWindow.i: source/windows/BattleChoiceWindow.cpp.i

.PHONY : source/windows/BattleChoiceWindow.i

# target to preprocess a source file
source/windows/BattleChoiceWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleChoiceWindow.cpp.i
.PHONY : source/windows/BattleChoiceWindow.cpp.i

source/windows/BattleChoiceWindow.s: source/windows/BattleChoiceWindow.cpp.s

.PHONY : source/windows/BattleChoiceWindow.s

# target to generate assembly for a file
source/windows/BattleChoiceWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/BattleChoiceWindow.cpp.s
.PHONY : source/windows/BattleChoiceWindow.cpp.s

source/windows/CommandWindow.o: source/windows/CommandWindow.cpp.o

.PHONY : source/windows/CommandWindow.o

# target to build an object file
source/windows/CommandWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/CommandWindow.cpp.o
.PHONY : source/windows/CommandWindow.cpp.o

source/windows/CommandWindow.i: source/windows/CommandWindow.cpp.i

.PHONY : source/windows/CommandWindow.i

# target to preprocess a source file
source/windows/CommandWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/CommandWindow.cpp.i
.PHONY : source/windows/CommandWindow.cpp.i

source/windows/CommandWindow.s: source/windows/CommandWindow.cpp.s

.PHONY : source/windows/CommandWindow.s

# target to generate assembly for a file
source/windows/CommandWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/CommandWindow.cpp.s
.PHONY : source/windows/CommandWindow.cpp.s

source/windows/EquipChoiceWindow.o: source/windows/EquipChoiceWindow.cpp.o

.PHONY : source/windows/EquipChoiceWindow.o

# target to build an object file
source/windows/EquipChoiceWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipChoiceWindow.cpp.o
.PHONY : source/windows/EquipChoiceWindow.cpp.o

source/windows/EquipChoiceWindow.i: source/windows/EquipChoiceWindow.cpp.i

.PHONY : source/windows/EquipChoiceWindow.i

# target to preprocess a source file
source/windows/EquipChoiceWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipChoiceWindow.cpp.i
.PHONY : source/windows/EquipChoiceWindow.cpp.i

source/windows/EquipChoiceWindow.s: source/windows/EquipChoiceWindow.cpp.s

.PHONY : source/windows/EquipChoiceWindow.s

# target to generate assembly for a file
source/windows/EquipChoiceWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipChoiceWindow.cpp.s
.PHONY : source/windows/EquipChoiceWindow.cpp.s

source/windows/EquipStatsWindow.o: source/windows/EquipStatsWindow.cpp.o

.PHONY : source/windows/EquipStatsWindow.o

# target to build an object file
source/windows/EquipStatsWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipStatsWindow.cpp.o
.PHONY : source/windows/EquipStatsWindow.cpp.o

source/windows/EquipStatsWindow.i: source/windows/EquipStatsWindow.cpp.i

.PHONY : source/windows/EquipStatsWindow.i

# target to preprocess a source file
source/windows/EquipStatsWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipStatsWindow.cpp.i
.PHONY : source/windows/EquipStatsWindow.cpp.i

source/windows/EquipStatsWindow.s: source/windows/EquipStatsWindow.cpp.s

.PHONY : source/windows/EquipStatsWindow.s

# target to generate assembly for a file
source/windows/EquipStatsWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/EquipStatsWindow.cpp.s
.PHONY : source/windows/EquipStatsWindow.cpp.s

source/windows/InfoWindow.o: source/windows/InfoWindow.cpp.o

.PHONY : source/windows/InfoWindow.o

# target to build an object file
source/windows/InfoWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/InfoWindow.cpp.o
.PHONY : source/windows/InfoWindow.cpp.o

source/windows/InfoWindow.i: source/windows/InfoWindow.cpp.i

.PHONY : source/windows/InfoWindow.i

# target to preprocess a source file
source/windows/InfoWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/InfoWindow.cpp.i
.PHONY : source/windows/InfoWindow.cpp.i

source/windows/InfoWindow.s: source/windows/InfoWindow.cpp.s

.PHONY : source/windows/InfoWindow.s

# target to generate assembly for a file
source/windows/InfoWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/InfoWindow.cpp.s
.PHONY : source/windows/InfoWindow.cpp.s

source/windows/ItemWindow.o: source/windows/ItemWindow.cpp.o

.PHONY : source/windows/ItemWindow.o

# target to build an object file
source/windows/ItemWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ItemWindow.cpp.o
.PHONY : source/windows/ItemWindow.cpp.o

source/windows/ItemWindow.i: source/windows/ItemWindow.cpp.i

.PHONY : source/windows/ItemWindow.i

# target to preprocess a source file
source/windows/ItemWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ItemWindow.cpp.i
.PHONY : source/windows/ItemWindow.cpp.i

source/windows/ItemWindow.s: source/windows/ItemWindow.cpp.s

.PHONY : source/windows/ItemWindow.s

# target to generate assembly for a file
source/windows/ItemWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/ItemWindow.cpp.s
.PHONY : source/windows/ItemWindow.cpp.s

source/windows/QuestInfoWindow.o: source/windows/QuestInfoWindow.cpp.o

.PHONY : source/windows/QuestInfoWindow.o

# target to build an object file
source/windows/QuestInfoWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/QuestInfoWindow.cpp.o
.PHONY : source/windows/QuestInfoWindow.cpp.o

source/windows/QuestInfoWindow.i: source/windows/QuestInfoWindow.cpp.i

.PHONY : source/windows/QuestInfoWindow.i

# target to preprocess a source file
source/windows/QuestInfoWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/QuestInfoWindow.cpp.i
.PHONY : source/windows/QuestInfoWindow.cpp.i

source/windows/QuestInfoWindow.s: source/windows/QuestInfoWindow.cpp.s

.PHONY : source/windows/QuestInfoWindow.s

# target to generate assembly for a file
source/windows/QuestInfoWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/QuestInfoWindow.cpp.s
.PHONY : source/windows/QuestInfoWindow.cpp.s

source/windows/SelectableWindow.o: source/windows/SelectableWindow.cpp.o

.PHONY : source/windows/SelectableWindow.o

# target to build an object file
source/windows/SelectableWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/SelectableWindow.cpp.o
.PHONY : source/windows/SelectableWindow.cpp.o

source/windows/SelectableWindow.i: source/windows/SelectableWindow.cpp.i

.PHONY : source/windows/SelectableWindow.i

# target to preprocess a source file
source/windows/SelectableWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/SelectableWindow.cpp.i
.PHONY : source/windows/SelectableWindow.cpp.i

source/windows/SelectableWindow.s: source/windows/SelectableWindow.cpp.s

.PHONY : source/windows/SelectableWindow.s

# target to generate assembly for a file
source/windows/SelectableWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/SelectableWindow.cpp.s
.PHONY : source/windows/SelectableWindow.cpp.s

source/windows/TextWindow.o: source/windows/TextWindow.cpp.o

.PHONY : source/windows/TextWindow.o

# target to build an object file
source/windows/TextWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/TextWindow.cpp.o
.PHONY : source/windows/TextWindow.cpp.o

source/windows/TextWindow.i: source/windows/TextWindow.cpp.i

.PHONY : source/windows/TextWindow.i

# target to preprocess a source file
source/windows/TextWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/TextWindow.cpp.i
.PHONY : source/windows/TextWindow.cpp.i

source/windows/TextWindow.s: source/windows/TextWindow.cpp.s

.PHONY : source/windows/TextWindow.s

# target to generate assembly for a file
source/windows/TextWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/TextWindow.cpp.s
.PHONY : source/windows/TextWindow.cpp.s

source/windows/VictoryWindow.o: source/windows/VictoryWindow.cpp.o

.PHONY : source/windows/VictoryWindow.o

# target to build an object file
source/windows/VictoryWindow.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/VictoryWindow.cpp.o
.PHONY : source/windows/VictoryWindow.cpp.o

source/windows/VictoryWindow.i: source/windows/VictoryWindow.cpp.i

.PHONY : source/windows/VictoryWindow.i

# target to preprocess a source file
source/windows/VictoryWindow.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/VictoryWindow.cpp.i
.PHONY : source/windows/VictoryWindow.cpp.i

source/windows/VictoryWindow.s: source/windows/VictoryWindow.cpp.s

.PHONY : source/windows/VictoryWindow.s

# target to generate assembly for a file
source/windows/VictoryWindow.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/VictoryWindow.cpp.s
.PHONY : source/windows/VictoryWindow.cpp.s

source/windows/Window.o: source/windows/Window.cpp.o

.PHONY : source/windows/Window.o

# target to build an object file
source/windows/Window.cpp.o:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/Window.cpp.o
.PHONY : source/windows/Window.cpp.o

source/windows/Window.i: source/windows/Window.cpp.i

.PHONY : source/windows/Window.i

# target to preprocess a source file
source/windows/Window.cpp.i:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/Window.cpp.i
.PHONY : source/windows/Window.cpp.i

source/windows/Window.s: source/windows/Window.cpp.s

.PHONY : source/windows/Window.s

# target to generate assembly for a file
source/windows/Window.cpp.s:
	$(MAKE) -f CMakeFiles/Asylia.dir/build.make CMakeFiles/Asylia.dir/source/windows/Window.cpp.s
.PHONY : source/windows/Window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Asylia"
	@echo "... edit_cache"
	@echo "... external/AndroidIO.o"
	@echo "... external/AndroidIO.i"
	@echo "... external/AndroidIO.s"
	@echo "... external/SLB.o"
	@echo "... external/SLB.i"
	@echo "... external/SLB.s"
	@echo "... source/Game.o"
	@echo "... source/Game.i"
	@echo "... source/Game.s"
	@echo "... source/activities/Activity.o"
	@echo "... source/activities/Activity.i"
	@echo "... source/activities/Activity.s"
	@echo "... source/activities/BattleActivity.o"
	@echo "... source/activities/BattleActivity.i"
	@echo "... source/activities/BattleActivity.s"
	@echo "... source/activities/EndActivity.o"
	@echo "... source/activities/EndActivity.i"
	@echo "... source/activities/EndActivity.s"
	@echo "... source/activities/EquipActivity.o"
	@echo "... source/activities/EquipActivity.i"
	@echo "... source/activities/EquipActivity.s"
	@echo "... source/activities/ItemActivity.o"
	@echo "... source/activities/ItemActivity.i"
	@echo "... source/activities/ItemActivity.s"
	@echo "... source/activities/LuaActivity.o"
	@echo "... source/activities/LuaActivity.i"
	@echo "... source/activities/LuaActivity.s"
	@echo "... source/activities/MapActivity.o"
	@echo "... source/activities/MapActivity.i"
	@echo "... source/activities/MapActivity.s"
	@echo "... source/activities/MenuActivity.o"
	@echo "... source/activities/MenuActivity.i"
	@echo "... source/activities/MenuActivity.s"
	@echo "... source/activities/MessageActivity.o"
	@echo "... source/activities/MessageActivity.i"
	@echo "... source/activities/MessageActivity.s"
	@echo "... source/activities/QuestActivity.o"
	@echo "... source/activities/QuestActivity.i"
	@echo "... source/activities/QuestActivity.s"
	@echo "... source/activities/SettingsActivity.o"
	@echo "... source/activities/SettingsActivity.i"
	@echo "... source/activities/SettingsActivity.s"
	@echo "... source/activities/TitleActivity.o"
	@echo "... source/activities/TitleActivity.i"
	@echo "... source/activities/TitleActivity.s"
	@echo "... source/core/Color.o"
	@echo "... source/core/Color.i"
	@echo "... source/core/Color.s"
	@echo "... source/core/LuaHandler.o"
	@echo "... source/core/LuaHandler.i"
	@echo "... source/core/LuaHandler.s"
	@echo "... source/core/Parameter.o"
	@echo "... source/core/Parameter.i"
	@echo "... source/core/Parameter.s"
	@echo "... source/core/SDLManager.o"
	@echo "... source/core/SDLManager.i"
	@echo "... source/core/SDLManager.s"
	@echo "... source/core/Sound.o"
	@echo "... source/core/Sound.i"
	@echo "... source/core/Sound.s"
	@echo "... source/core/TimeManager.o"
	@echo "... source/core/TimeManager.i"
	@echo "... source/core/TimeManager.s"
	@echo "... source/core/XMLFile.o"
	@echo "... source/core/XMLFile.i"
	@echo "... source/core/XMLFile.s"
	@echo "... source/display/Animation.o"
	@echo "... source/display/Animation.i"
	@echo "... source/display/Animation.s"
	@echo "... source/display/AnimationManager.o"
	@echo "... source/display/AnimationManager.i"
	@echo "... source/display/AnimationManager.s"
	@echo "... source/display/Font.o"
	@echo "... source/display/Font.i"
	@echo "... source/display/Font.s"
	@echo "... source/display/GameWindow.o"
	@echo "... source/display/GameWindow.i"
	@echo "... source/display/GameWindow.s"
	@echo "... source/display/Image.o"
	@echo "... source/display/Image.i"
	@echo "... source/display/Image.s"
	@echo "... source/display/Interface.o"
	@echo "... source/display/Interface.i"
	@echo "... source/display/Interface.s"
	@echo "... source/display/Map.o"
	@echo "... source/display/Map.i"
	@echo "... source/display/Map.s"
	@echo "... source/display/MapManager.o"
	@echo "... source/display/MapManager.i"
	@echo "... source/display/MapManager.s"
	@echo "... source/display/Sprite.o"
	@echo "... source/display/Sprite.i"
	@echo "... source/display/Sprite.s"
	@echo "... source/display/SpriteAnimationManager.o"
	@echo "... source/display/SpriteAnimationManager.i"
	@echo "... source/display/SpriteAnimationManager.s"
	@echo "... source/display/Timer.o"
	@echo "... source/display/Timer.i"
	@echo "... source/display/Timer.s"
	@echo "... source/entities/Actor.o"
	@echo "... source/entities/Actor.i"
	@echo "... source/entities/Actor.s"
	@echo "... source/entities/Battler.o"
	@echo "... source/entities/Battler.i"
	@echo "... source/entities/Battler.s"
	@echo "... source/entities/Character.o"
	@echo "... source/entities/Character.i"
	@echo "... source/entities/Character.s"
	@echo "... source/entities/Enemy.o"
	@echo "... source/entities/Enemy.i"
	@echo "... source/entities/Enemy.s"
	@echo "... source/entities/Player.o"
	@echo "... source/entities/Player.i"
	@echo "... source/entities/Player.s"
	@echo "... source/events/Event.o"
	@echo "... source/events/Event.i"
	@echo "... source/events/Event.s"
	@echo "... source/events/EventAction.o"
	@echo "... source/events/EventAction.i"
	@echo "... source/events/EventAction.s"
	@echo "... source/events/EventInterpreter.o"
	@echo "... source/events/EventInterpreter.i"
	@echo "... source/events/EventInterpreter.s"
	@echo "... source/events/EventListener.o"
	@echo "... source/events/EventListener.i"
	@echo "... source/events/EventListener.s"
	@echo "... source/main.o"
	@echo "... source/main.i"
	@echo "... source/main.s"
	@echo "... source/managers/ActivityManager.o"
	@echo "... source/managers/ActivityManager.i"
	@echo "... source/managers/ActivityManager.s"
	@echo "... source/managers/BattlerManager.o"
	@echo "... source/managers/BattlerManager.i"
	@echo "... source/managers/BattlerManager.s"
	@echo "... source/managers/CharacterManager.o"
	@echo "... source/managers/CharacterManager.i"
	@echo "... source/managers/CharacterManager.s"
	@echo "... source/managers/EventManager.o"
	@echo "... source/managers/EventManager.i"
	@echo "... source/managers/EventManager.s"
	@echo "... source/managers/ItemManager.o"
	@echo "... source/managers/ItemManager.i"
	@echo "... source/managers/ItemManager.s"
	@echo "... source/managers/LanguageManager.o"
	@echo "... source/managers/LanguageManager.i"
	@echo "... source/managers/LanguageManager.s"
	@echo "... source/managers/QuestManager.o"
	@echo "... source/managers/QuestManager.i"
	@echo "... source/managers/QuestManager.s"
	@echo "... source/managers/SaveManager.o"
	@echo "... source/managers/SaveManager.i"
	@echo "... source/managers/SaveManager.s"
	@echo "... source/managers/TroopManager.o"
	@echo "... source/managers/TroopManager.i"
	@echo "... source/managers/TroopManager.s"
	@echo "... source/objects/Armor.o"
	@echo "... source/objects/Armor.i"
	@echo "... source/objects/Armor.s"
	@echo "... source/objects/Battle.o"
	@echo "... source/objects/Battle.i"
	@echo "... source/objects/Battle.s"
	@echo "... source/objects/BattleAction.o"
	@echo "... source/objects/BattleAction.i"
	@echo "... source/objects/BattleAction.s"
	@echo "... source/objects/Equipment.o"
	@echo "... source/objects/Equipment.i"
	@echo "... source/objects/Equipment.s"
	@echo "... source/objects/Inventory.o"
	@echo "... source/objects/Inventory.i"
	@echo "... source/objects/Inventory.s"
	@echo "... source/objects/Item.o"
	@echo "... source/objects/Item.i"
	@echo "... source/objects/Item.s"
	@echo "... source/objects/Keyboard.o"
	@echo "... source/objects/Keyboard.i"
	@echo "... source/objects/Keyboard.s"
	@echo "... source/objects/Skill.o"
	@echo "... source/objects/Skill.i"
	@echo "... source/objects/Skill.s"
	@echo "... source/objects/Troop.o"
	@echo "... source/objects/Troop.i"
	@echo "... source/objects/Troop.s"
	@echo "... source/objects/Weapon.o"
	@echo "... source/objects/Weapon.i"
	@echo "... source/objects/Weapon.s"
	@echo "... source/quests/Quest.o"
	@echo "... source/quests/Quest.i"
	@echo "... source/quests/Quest.s"
	@echo "... source/quests/QuestObjective.o"
	@echo "... source/quests/QuestObjective.i"
	@echo "... source/quests/QuestObjective.s"
	@echo "... source/windows/ActorChoiceWindow.o"
	@echo "... source/windows/ActorChoiceWindow.i"
	@echo "... source/windows/ActorChoiceWindow.s"
	@echo "... source/windows/ActorStatsWindow.o"
	@echo "... source/windows/ActorStatsWindow.i"
	@echo "... source/windows/ActorStatsWindow.s"
	@echo "... source/windows/BattleActionWindow.o"
	@echo "... source/windows/BattleActionWindow.i"
	@echo "... source/windows/BattleActionWindow.s"
	@echo "... source/windows/BattleChoiceWindow.o"
	@echo "... source/windows/BattleChoiceWindow.i"
	@echo "... source/windows/BattleChoiceWindow.s"
	@echo "... source/windows/CommandWindow.o"
	@echo "... source/windows/CommandWindow.i"
	@echo "... source/windows/CommandWindow.s"
	@echo "... source/windows/EquipChoiceWindow.o"
	@echo "... source/windows/EquipChoiceWindow.i"
	@echo "... source/windows/EquipChoiceWindow.s"
	@echo "... source/windows/EquipStatsWindow.o"
	@echo "... source/windows/EquipStatsWindow.i"
	@echo "... source/windows/EquipStatsWindow.s"
	@echo "... source/windows/InfoWindow.o"
	@echo "... source/windows/InfoWindow.i"
	@echo "... source/windows/InfoWindow.s"
	@echo "... source/windows/ItemWindow.o"
	@echo "... source/windows/ItemWindow.i"
	@echo "... source/windows/ItemWindow.s"
	@echo "... source/windows/QuestInfoWindow.o"
	@echo "... source/windows/QuestInfoWindow.i"
	@echo "... source/windows/QuestInfoWindow.s"
	@echo "... source/windows/SelectableWindow.o"
	@echo "... source/windows/SelectableWindow.i"
	@echo "... source/windows/SelectableWindow.s"
	@echo "... source/windows/TextWindow.o"
	@echo "... source/windows/TextWindow.i"
	@echo "... source/windows/TextWindow.s"
	@echo "... source/windows/VictoryWindow.o"
	@echo "... source/windows/VictoryWindow.i"
	@echo "... source/windows/VictoryWindow.s"
	@echo "... source/windows/Window.o"
	@echo "... source/windows/Window.i"
	@echo "... source/windows/Window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

